// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/sync.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LockManager_Ping_FullMethodName        = "/sync.LockManager/Ping"
	LockManager_AcquireLock_FullMethodName = "/sync.LockManager/AcquireLock"
	LockManager_ReleaseLock_FullMethodName = "/sync.LockManager/ReleaseLock"
)

// LockManagerClient is the client API for LockManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LockManagerClient interface {
	// Health check to verify the daemon is alive
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Attempt to claim a resource
	AcquireLock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockResponse, error)
	// Release a claimed resource
	ReleaseLock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockResponse, error)
}

type lockManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewLockManagerClient(cc grpc.ClientConnInterface) LockManagerClient {
	return &lockManagerClient{cc}
}

func (c *lockManagerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, LockManager_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockManagerClient) AcquireLock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockResponse)
	err := c.cc.Invoke(ctx, LockManager_AcquireLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockManagerClient) ReleaseLock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockResponse)
	err := c.cc.Invoke(ctx, LockManager_ReleaseLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LockManagerServer is the server API for LockManager service.
// All implementations must embed UnimplementedLockManagerServer
// for forward compatibility.
type LockManagerServer interface {
	// Health check to verify the daemon is alive
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Attempt to claim a resource
	AcquireLock(context.Context, *LockRequest) (*LockResponse, error)
	// Release a claimed resource
	ReleaseLock(context.Context, *LockRequest) (*LockResponse, error)
	mustEmbedUnimplementedLockManagerServer()
}

// UnimplementedLockManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLockManagerServer struct{}

func (UnimplementedLockManagerServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedLockManagerServer) AcquireLock(context.Context, *LockRequest) (*LockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcquireLock not implemented")
}
func (UnimplementedLockManagerServer) ReleaseLock(context.Context, *LockRequest) (*LockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseLock not implemented")
}
func (UnimplementedLockManagerServer) mustEmbedUnimplementedLockManagerServer() {}
func (UnimplementedLockManagerServer) testEmbeddedByValue()                     {}

// UnsafeLockManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LockManagerServer will
// result in compilation errors.
type UnsafeLockManagerServer interface {
	mustEmbedUnimplementedLockManagerServer()
}

func RegisterLockManagerServer(s grpc.ServiceRegistrar, srv LockManagerServer) {
	// If the following call panics, it indicates UnimplementedLockManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LockManager_ServiceDesc, srv)
}

func _LockManager_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockManagerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockManager_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockManagerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockManager_AcquireLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockManagerServer).AcquireLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockManager_AcquireLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockManagerServer).AcquireLock(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockManager_ReleaseLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockManagerServer).ReleaseLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockManager_ReleaseLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockManagerServer).ReleaseLock(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LockManager_ServiceDesc is the grpc.ServiceDesc for LockManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LockManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sync.LockManager",
	HandlerType: (*LockManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _LockManager_Ping_Handler,
		},
		{
			MethodName: "AcquireLock",
			Handler:    _LockManager_AcquireLock_Handler,
		},
		{
			MethodName: "ReleaseLock",
			Handler:    _LockManager_ReleaseLock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sync.proto",
}
